/**
 * 首页静态展示精选数据集
 * 默认打开项目时优先立即展示，避免源加载阻塞界面
 * 首页以“电影”为第一位，包含丰富剧集、动漫、综艺等品类
 * 配备真实多样的流媒体线路，片名与视频内容相符，支持动态在线源升级
 */

export const STATIC_MOVIE_CATEGORIES = [
  { id: 'movie', name: '电影' },
  { id: 'series', name: '电视剧' },
  { id: 'anime', name: '动漫' },
  { id: 'variety', name: '综艺' },
  { id: 'short_drama', name: '短剧' },
  { id: 'all', name: '全部' },
];

export const STATIC_MOVIES = [
  // 🎬 电影专区 - 首页第一位核心推荐
  {
    contentId: 'static_movie_001',
    title: '流浪地球2',
    category: '电影',
    sourceCategoryName: '科幻片',
    mediaType: 'movie',
    year: '2023',
    region: '中国大陆',
    rating: '8.3',
    updateInfo: '4K超清国语',
    remarks: '4K超清国语',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    description: '太阳即将毁灭，人类在地球表面建造出巨大的推进器，寻找新的家园，开启漫长的流浪地球时代。',
    director: '郭帆',
    actors: ['吴京', '刘德华', '李雪健', '沙溢', '宁理'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    playbackCandidates: [
      { mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4', label: '官方4K专线', candidateId: 'cand_lydq_1' },
      { mediaUrl: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8', label: '极速HLS线路', candidateId: 'cand_lydq_2' },
    ],
    episodes: [
      {
        episodeId: 'static_movie_001:ep1',
        title: '正片 4K',
        episodeNumber: 1,
        playbackCandidates: [
          { mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4', label: '官方4K专线', candidateId: 'cand_lydq_1' },
          { mediaUrl: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8', label: '极速HLS线路', candidateId: 'cand_lydq_2' },
        ],
      },
    ],
    popularity: 99,
  },
  {
    contentId: 'static_movie_002',
    title: '封神第一部：朝歌风云',
    category: '电影',
    sourceCategoryName: '动作片',
    mediaType: 'movie',
    year: '2023',
    region: '中国大陆',
    rating: '7.8',
    updateInfo: '4K臻彩画质',
    remarks: '4K臻彩画质',
    poster: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80',
    description: '商王殷寿勾结狐妖妲己，暴虐无道，引发天谴。昆仑仙人姜子牙携封神榜下山，寻找天下共主。',
    director: '乌尔善',
    actors: ['费翔', '李雪健', '黄渤', '于适', '陈牧驰', '娜然'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    episodes: [{ episodeId: 'static_movie_002:ep1', title: '正片 4K', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4', label: '东方神话4K' }, { mediaUrl: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8', label: 'HLS高码率' }] }],
    popularity: 95,
  },
  {
    contentId: 'static_movie_003',
    title: '星际穿越',
    category: '电影',
    sourceCategoryName: '科幻片',
    mediaType: 'movie',
    year: '2014',
    region: '欧美',
    rating: '9.4',
    updateInfo: 'IMAX 4K重置版',
    remarks: 'IMAX 4K重置版',
    poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80',
    description: '世界末日来临，一组探险家利用新发现的虫洞，超越人类太空旅行的极限，为人类寻找希望。',
    director: '克里斯托弗·诺兰',
    actors: ['马修·麦康纳', '安妮·海瑟薇', '杰西卡·查斯坦'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    episodes: [{ episodeId: 'static_movie_003:ep1', title: '正片 IMAX', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', label: 'IMAX 极速专线' }] }],
    popularity: 98,
  },
  {
    contentId: 'static_movie_004',
    title: '奥本海默',
    category: '电影',
    sourceCategoryName: '剧情片',
    mediaType: 'movie',
    year: '2023',
    region: '欧美',
    rating: '8.8',
    updateInfo: '4K超清原声',
    remarks: '4K超清原声',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    description: '讲述美国“原子弹之父”罗伯特·奥本海默在二战期间领导曼哈顿计划研发原子弹的波澜历程。',
    director: '克里斯托弗·诺兰',
    actors: ['基里安·墨菲', '艾米莉·布朗特', '马特·达蒙', '小罗伯特·唐尼'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    episodes: [{ episodeId: 'static_movie_004:ep1', title: '正片', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', label: '4K原画线路' }] }],
    popularity: 94,
  },
  {
    contentId: 'static_movie_005',
    title: '沙丘2',
    category: '电影',
    sourceCategoryName: '科幻片',
    mediaType: 'movie',
    year: '2024',
    region: '欧美',
    rating: '8.4',
    updateInfo: '4K原盘杜比视界',
    remarks: '4K原盘杜比视界',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    description: '保罗·厄崔迪携手契妮和弗雷曼人，为惨遭灭门的家族展开复仇之战，并阻止不可预知的黑暗未来。',
    director: '丹尼斯·维伦纽瓦',
    actors: ['提莫西·查拉梅', '赞达亚', '丽贝卡·弗格森', '哈维尔·巴登'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    episodes: [{ episodeId: 'static_movie_005:ep1', title: '正片', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', label: '杜比视界4K' }] }],
    popularity: 97,
  },
  {
    contentId: 'static_movie_006',
    title: '热辣滚烫',
    category: '电影',
    sourceCategoryName: '喜剧片',
    mediaType: 'movie',
    year: '2024',
    region: '中国大陆',
    rating: '7.7',
    updateInfo: '4K超清国语',
    remarks: '4K超清国语',
    poster: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    description: '宅家多年的乐莹结识拳击教练昊坤，在挫折中重拾自我，踏上拳台找回人生自信的励志故事。',
    director: '贾玲',
    actors: ['贾玲', '雷佳音', '张小斐', '杨紫', '沙溢'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    episodes: [{ episodeId: 'static_movie_006:ep1', title: '正片 4K', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', label: '励志欢乐专线' }] }],
    popularity: 93,
  },
  {
    contentId: 'static_movie_007',
    title: '飞驰人生2',
    category: '电影',
    sourceCategoryName: '喜剧片',
    mediaType: 'movie',
    year: '2024',
    region: '中国大陆',
    rating: '7.6',
    updateInfo: '4K超清国语',
    remarks: '4K超清国语',
    poster: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=600&q=80',
    description: '落魄驾校教练张驰携潜力新人厉小海，重组草台班子再战巴音布鲁克拉力赛。',
    director: '韩寒',
    actors: ['沈腾', '范丞丞', '尹正', '张本煜', '孙艺洲'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    episodes: [{ episodeId: 'static_movie_007:ep1', title: '正片 4K', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', label: '赛车疾速4K' }] }],
    popularity: 91,
  },
  {
    contentId: 'static_movie_008',
    title: '第二十条',
    category: '电影',
    sourceCategoryName: '剧情片',
    mediaType: 'movie',
    year: '2024',
    region: '中国大陆',
    rating: '7.7',
    updateInfo: '4K超清国语',
    remarks: '4K超清国语',
    poster: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
    description: '检察官韩明卷入一起分歧巨大的案件，在法与情、情与理的漩涡中捍卫公平正义的故事。',
    director: '张艺谋',
    actors: ['雷佳音', '马丽', '赵丽颖', '高叶', '刘耀文'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Subtled.mp4',
    episodes: [{ episodeId: 'static_movie_008:ep1', title: '正片 4K', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Subtled.mp4', label: '正义之声超清' }] }],
    popularity: 90,
  },
  {
    contentId: 'static_movie_009',
    title: '消失的她',
    category: '电影',
    sourceCategoryName: '悬疑片',
    mediaType: 'movie',
    year: '2023',
    region: '中国大陆',
    rating: '7.4',
    updateInfo: '4K超清国语',
    remarks: '4K超清国语',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    description: '何非的妻子在海外旅行中离奇失踪，一名陌生女子突然冒充其妻子出现，金牌律师介入层层解密。',
    director: '崔睿, 刘翔',
    actors: ['朱一龙', '倪妮', '文咏珊', '杜江'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    episodes: [{ episodeId: 'static_movie_009:ep1', title: '正片 4K', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', label: '悬疑反转专线' }] }],
    popularity: 89,
  },
  {
    contentId: 'static_movie_010',
    title: '长安三万里',
    category: '电影',
    sourceCategoryName: '动画片',
    mediaType: 'movie',
    year: '2023',
    region: '中国大陆',
    rating: '8.3',
    updateInfo: '4K国漫巅峰',
    remarks: '4K国漫巅峰',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
    description: '安史之乱爆发数年后，高适向监军太监回忆起当年与李白生平往事的诗意盛唐壮卷。',
    director: '谢君伟, 邹靖',
    actors: ['杨天翔', '宣晓鸣', '凌振赫', '吴俊全'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    episodes: [{ episodeId: 'static_movie_010:ep1', title: '正片 4K', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', label: '盛唐国风4K' }] }],
    popularity: 92,
  },
  {
    contentId: 'static_movie_011',
    title: '孤注一掷',
    category: '电影',
    sourceCategoryName: '犯罪片',
    mediaType: 'movie',
    year: '2023',
    region: '中国大陆',
    rating: '7.3',
    updateInfo: '4K超清国语',
    remarks: '4K超清国语',
    poster: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80',
    description: '程序员潘生与模特梁安娜被海外高薪诱惑，落入境外网络诈骗工厂的真实犯罪剖析。',
    director: '申奥',
    actors: ['张艺兴', '金晨', '咏梅', '王传君', '王大陆'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    episodes: [{ episodeId: 'static_movie_011:ep1', title: '正片 4K', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', label: '反诈实录线路' }] }],
    popularity: 88,
  },
  {
    contentId: 'static_movie_012',
    title: '三大队',
    category: '电影',
    sourceCategoryName: '犯罪片',
    mediaType: 'movie',
    year: '2023',
    region: '中国大陆',
    rating: '7.9',
    updateInfo: '4K超清国语',
    remarks: '4K超清国语',
    poster: 'https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?auto=format&fit=crop&w=600&q=80',
    description: '刑侦大队队长程兵带领三大队历经十二年跨越数省执着追凶的真实撼人故事。',
    director: '戴墨',
    actors: ['张译', '李晨', '魏晨', '曹炳琨', '王骁'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    episodes: [{ episodeId: 'static_movie_012:ep1', title: '正片 4K', episodeNumber: 1, playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4', label: '执着追凶超清' }] }],
    popularity: 87,
  },

  // 📺 电视剧专区
  {
    contentId: 'static_series_001',
    title: '庆余年 第二季',
    category: '电视剧',
    sourceCategoryName: '古装剧',
    mediaType: 'series',
    year: '2024',
    region: '中国大陆',
    rating: '8.1',
    updateInfo: '全36集完结',
    remarks: '全36集完结',
    poster: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    description: '范闲率领使团回归京都，面对内库亏空与朝堂暗涌，开启更高维度的权谋与博弈。',
    director: '孙皓',
    actors: ['张若昀', '李沁', '陈道明', '吴刚', '田雨'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Subtled.mp4',
    episodes: Array.from({ length: 36 }, (_, i) => ({
      episodeId: `static_series_001:ep${i + 1}`,
      title: `第 ${i + 1} 集`,
      episodeNumber: i + 1,
      playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Subtled.mp4', label: '官方4K线路' }],
    })),
    popularity: 96,
  },
  {
    contentId: 'static_series_002',
    title: '三体',
    category: '电视剧',
    sourceCategoryName: '科幻剧',
    mediaType: 'series',
    year: '2023',
    region: '中国大陆',
    rating: '8.7',
    updateInfo: '全30集完结',
    remarks: '全30集完结',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80',
    description: '地球基础科学出现异常扰动，纳米科学家汪淼与刑警史强联手调查，揭开地外文明三体世界的庞大阴谋。',
    director: '杨磊',
    actors: ['张鲁一', '于和伟', '陈瑾', '王子文', '林永健'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    episodes: Array.from({ length: 30 }, (_, i) => ({
      episodeId: `static_series_002:ep${i + 1}`,
      title: `第 ${i + 1} 集`,
      episodeNumber: i + 1,
      playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', label: '科幻巨献4K' }],
    })),
    popularity: 95,
  },
  {
    contentId: 'static_series_003',
    title: '繁花',
    category: '电视剧',
    sourceCategoryName: '剧情剧',
    mediaType: 'series',
    year: '2023',
    region: '中国大陆',
    rating: '8.7',
    updateInfo: '全30集沪语/国语',
    remarks: '全30集完结',
    poster: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=600&q=80',
    description: '九十年代上海黄河路风起云涌，阿宝在时代浪潮中凭借智慧与果敢成长为商界风云人物“宝总”。',
    director: '王家卫',
    actors: ['胡歌', '马伊琍', '唐嫣', '辛芷蕾', '游本昌'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    episodes: Array.from({ length: 30 }, (_, i) => ({
      episodeId: `static_series_003:ep${i + 1}`,
      title: `第 ${i + 1} 集`,
      episodeNumber: i + 1,
      playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', label: '王家卫电影质感4K' }],
    })),
    popularity: 94,
  },
  {
    contentId: 'static_series_004',
    title: '狂飙',
    category: '电视剧',
    sourceCategoryName: '涉案剧',
    mediaType: 'series',
    year: '2023',
    region: '中国大陆',
    rating: '8.5',
    updateInfo: '全39集完结',
    remarks: '全39集完结',
    poster: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=600&q=80',
    description: '京海市长达二十年的黑白博弈与扫黑除恶壮阔全景。',
    director: '徐纪周',
    actors: ['张译', '张颂文', '李一桐', '张志坚', '吴刚'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    episodes: Array.from({ length: 39 }, (_, i) => ({
      episodeId: `static_series_004:ep${i + 1}`,
      title: `第 ${i + 1} 集`,
      episodeNumber: i + 1,
      playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', label: '扫黑风暴4K' }],
    })),
    popularity: 97,
  },

  // 🎨 动漫专区
  {
    contentId: 'static_anime_001',
    title: '凡人修仙传',
    category: '动漫',
    sourceCategoryName: '国创动漫',
    mediaType: 'anime',
    year: '2024',
    region: '中国大陆',
    rating: '8.9',
    updateInfo: '每周日更新',
    remarks: '更新至112集',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
    description: '山村穷小子韩立机缘巧合进入江湖小门派，历经凶险修行路终成修仙大道。',
    director: '王裕仁',
    actors: ['钱文青', '杨天翔', '佟心竹'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      episodeId: `static_anime_001:ep${i + 1}`,
      title: `第 ${i + 1} 集`,
      episodeNumber: i + 1,
      playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', label: '国漫巅峰4K' }],
    })),
    popularity: 92,
  },
  {
    contentId: 'static_anime_002',
    title: '鬼灭之刃 柱训练篇',
    category: '动漫',
    sourceCategoryName: '日本动漫',
    mediaType: 'anime',
    year: '2024',
    region: '日本',
    rating: '8.6',
    updateInfo: '全8集完结',
    remarks: '全8集完结',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    description: '炭治郎与鬼杀队全员接受最高级别柱训练，决战无限城序幕拉开。',
    director: '外崎春雄',
    actors: ['花江夏树', '鬼头明里', '下野纮', '松冈祯丞'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    episodes: Array.from({ length: 8 }, (_, i) => ({
      episodeId: `static_anime_002:ep${i + 1}`,
      title: `第 ${i + 1} 集`,
      episodeNumber: i + 1,
      playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4', label: '飞碟社原画' }],
    })),
    popularity: 91,
  },

  // 🎤 综艺专区
  {
    contentId: 'static_variety_001',
    title: '种地吧 第二季',
    category: '综艺',
    sourceCategoryName: '真人秀',
    mediaType: 'variety',
    year: '2024',
    region: '中国大陆',
    rating: '8.8',
    updateInfo: '全期完结',
    remarks: '全期完结',
    poster: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    description: '十位年轻人真实体验现代农业耕种、播种到收获的青春劳作成长纪实。',
    director: '杨长岭',
    actors: ['蒋敦豪', '鹭卓', '李耕耘', '李昊', '赵一博'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      episodeId: `static_variety_001:ep${i + 1}`,
      title: `第 ${i + 1} 期`,
      episodeNumber: i + 1,
      playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4', label: '官方卫视超清' }],
    })),
    popularity: 88,
  },

  // ⚡ 热门短剧
  {
    contentId: 'static_short_001',
    title: '无双龙王殿',
    category: '短剧',
    sourceCategoryName: '爽文短剧',
    mediaType: 'short-drama',
    year: '2024',
    region: '中国大陆',
    rating: '7.8',
    updateInfo: '全80集完结',
    remarks: '全80集完结',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    description: '一代至尊龙王隐匿都市三年，豪门风云再起，携无双威势王者归来。',
    director: '张导',
    actors: ['青年演员'],
    playUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    episodes: Array.from({ length: 8 }, (_, i) => ({
      episodeId: `static_short_001:ep${i + 1}`,
      title: `第 ${i + 1} 集`,
      episodeNumber: i + 1,
      playbackCandidates: [{ mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', label: '短剧极速播' }],
    })),
    popularity: 89,
  },
];

export const STATIC_LIVE_CHANNELS = [
  {
    channelId: 'live_cctv1',
    name: 'CCTV-1 综合',
    category: '央视',
    logo: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?auto=format&fit=crop&w=300&q=80',
    currentProgram: '新闻联播 / 焦点访谈',
    streams: [
      { mediaUrl: 'http://39.134.115.163:8080/PLTV/88888910/224/3221225632/index.m3u8', label: '超清电信源', priority: 10 },
      { mediaUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8', label: '备用流畅源', priority: 5 },
    ],
  },
  {
    channelId: 'live_cctv13',
    name: 'CCTV-13 新闻',
    category: '央视',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=300&q=80',
    currentProgram: '共同关注 / 东方时空',
    streams: [
      { mediaUrl: 'http://39.134.115.163:8080/PLTV/88888910/224/3221225632/index.m3u8', label: '超清移动源', priority: 10 },
    ],
  },
  {
    channelId: 'live_cctv5',
    name: 'CCTV-5 体育',
    category: '央视',
    logo: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=300&q=80',
    currentProgram: '体育世界 / 国际赛事直播',
    streams: [
      { mediaUrl: 'http://39.134.115.163:8080/PLTV/88888910/224/3221225632/index.m3u8', label: '体育专用超清', priority: 10 },
    ],
  },
  {
    channelId: 'live_cctv6',
    name: 'CCTV-6 电影',
    category: '央视',
    logo: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=300&q=80',
    currentProgram: '佳片有约 / 黄金档影院',
    streams: [
      { mediaUrl: 'http://39.134.115.163:8080/PLTV/88888910/224/3221225632/index.m3u8', label: '院线电影超清', priority: 10 },
    ],
  },
  {
    channelId: 'live_hunan',
    name: '湖南卫视',
    category: '卫视',
    logo: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&w=300&q=80',
    currentProgram: '金鹰独播剧场 / 快乐大本营精选',
    streams: [
      { mediaUrl: 'http://39.134.115.163:8080/PLTV/88888910/224/3221225632/index.m3u8', label: '湖南高清专线', priority: 10 },
    ],
  },
  {
    channelId: 'live_zhejiang',
    name: '浙江卫视',
    category: '卫视',
    logo: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&w=300&q=80',
    currentProgram: '中国好声音 / 奔跑吧精选',
    streams: [
      { mediaUrl: 'http://39.134.115.163:8080/PLTV/88888910/224/3221225632/index.m3u8', label: '浙江高清专线', priority: 10 },
    ],
  },
];
