import { createChannelIdentity, createChannelId, createEpgProgramId, createSourceChannelId, createStreamId, getEpgProgramStatus } from '../core__models__live.js';
import { inferLiveProtocolFromUrl } from '../core__playback__streamSniffer.js';
import { parseLiveUrl } from '../core__playback__liveUrl.js';

// Canonical and fallback channel identity
function clean(value){return String(value??'').trim().toLocaleLowerCase();}
export function resolveCanonicalChannelId({canonicalId='',channelKey='',name='' }={}){const canonical=clean(canonicalId);if(canonical)return canonical;const key=clean(channelKey);if(key)return key;return '';}
export function createSourceChannelIdentity(sourceId,sourceItemId){return `source-channel:${clean(sourceId)}:${clean(sourceItemId)}`;}
export function createFallbackChannelIdentity({sourceId,sourceItemId}){return `source:${clean(sourceId)}:${clean(sourceItemId)}`;}
export function createCanonicalChannelIdentity(canonicalId){return canonicalId?`canonical:${clean(canonicalId)}`:'';}
export function createDisplayNameKey(name){return clean(name).replace(/\s+/g,' ');}

// Adapter capability definitions
export const LiveCapability = Object.freeze({ CATEGORIES:'categories', CHANNELS:'channels', STREAMS:'streams', MULTI_STREAM:'multiStream', EPG:'epg', LOGO:'logo', CURRENT_PROGRAM:'currentProgram', UPCOMING_PROGRAM:'upcomingProgram', SEARCH:'search', FAVORITE_METADATA:'favoriteMetadata' });
export function normalizeLiveCapabilities(input = {}) { const result=Object.values(LiveCapability).reduce((out,key)=>{out[key]=false;return out;},{}); if(Array.isArray(input)){input.forEach(key=>{if(key in result) result[key]=true;});} else Object.assign(result,input); return Object.freeze(result); }
export const defaultLiveCapabilities = normalizeLiveCapabilities({categories:true,channels:true,streams:true,multiStream:true,epg:false,logo:true,currentProgram:false,upcomingProgram:false,search:false,favoriteMetadata:true});

// Normalized channel, stream and EPG models
function normalizeStream({sourceId,sourceItemId,stream,index}){const url=String(stream?.url??stream?.mediaUrl??'').trim();if(!url)return null;const parsedUrl=parseLiveUrl(url);return {streamId:stream.streamId??createStreamId(sourceId,sourceItemId,index),sourceId,sourceChannelId:createSourceChannelId(sourceId,sourceItemId),sourceItemId:stream.sourceItemId??sourceItemId,url,urlValid:parsedUrl.ok,urlError:parsedUrl.ok?null:parsedUrl.code,networkFamily:parsedUrl.networkFamily,protocol:normalizeProtocol(stream.protocol,url),label:stream.label||`线路 ${index+1}`,quality:stream.quality??'',resolution:stream.resolution??'',priority:Number.isFinite(stream.priority)?stream.priority:-index,status:stream.status??'unknown',lastCheckedAt:stream.lastCheckedAt??null,failureCode:stream.failureCode??null,failureCount:Number(stream.failureCount)||0,updatedAt:stream.updatedAt??Date.now(),expiresAt:stream.expiresAt??null,headers:stream.headers??{},cookies:stream.cookies??'',referer:stream.referer??'',userAgent:stream.userAgent??''};}
export function normalizeLiveChannel({sourceId,item,index=0,capabilities={}}){const sourceItemId=String(item.sourceItemId??item.id??`item-${index+1}`).trim();const canonicalId=resolveCanonicalChannelId({canonicalId:item.canonicalId??item.globalId??item.externalId??'',channelKey:item.channelKey??'',name:item.name});const identity=createChannelIdentity({canonicalId,channelKey:item.channelKey,name:item.name,sourceId,sourceItemId});const sourceChannelId=createSourceChannelId(sourceId,sourceItemId);const channelId=createChannelId(sourceId,sourceItemId,identity);const rawStreams=item.streams??(item.stream?[item.stream]:[]);const streams=rawStreams.map((stream,i)=>normalizeStream({sourceId,sourceItemId,stream,index:i})).filter(Boolean);const epg=normalizeEPG(channelId,item.epg??[]);return {channelId,canonicalChannelId:canonicalId||null,name:item.name||sourceItemId,nameKey:createDisplayNameKey(item.name||sourceItemId),logo:item.logo||'',categoryId:item.categoryId??item.categoryKey??item.category??'',category:item.category||'未分类',sourceRefs:[{sourceId,sourceChannelId,sourceItemId,canonicalChannelId:canonicalId||null,capabilities:{...capabilities}}],capabilities:{...capabilities},streams,epg,status:(streams.length || item.deferredRef)?'available':'unavailable',sourceOrder:Number.isFinite(item.sourceOrder)?item.sourceOrder:index,systemOrder:Number.isFinite(item.systemOrder)?item.systemOrder:index,sourcePriority:Number.isFinite(item.sourcePriority)?item.sourcePriority:0,userOrder:Number.isFinite(item.userOrder)?item.userOrder:null,description:item.description??'',currentProgram:item.currentProgram??null,upcomingProgram:item.upcomingProgram??null,syncAt:Date.now(),deferredRef:item.deferredRef??null};}
export function mergeLiveChannels(channels=[]){const byId=new Map();for(const channel of channels){if(!channel?.channelId)continue;const existing=byId.get(channel.channelId);if(!existing){byId.set(channel.channelId,{...channel,sourceRefs:[...(channel.sourceRefs??[])],streams:[...(channel.streams??[])],epg:[...(channel.epg??[])],availableSourceCount:channel.status==='available'?1:0});continue;}existing.sourceRefs.push(...(channel.sourceRefs??[]).filter(ref=>!existing.sourceRefs.some(x=>x.sourceChannelId===ref.sourceChannelId)));const knownStreams=new Set(existing.streams.map(s=>s.streamId));existing.streams.push(...(channel.streams??[]).filter(s=>!knownStreams.has(s.streamId)));const knownPrograms=new Set(existing.epg.map(p=>p.programId));existing.epg.push(...(channel.epg??[]).filter(p=>!knownPrograms.has(p.programId)));existing.capabilities={...existing.capabilities,...channel.capabilities};existing.availableSourceCount=existing.sourceRefs.filter(ref=>existing.streams.some(s=>s.sourceChannelId===ref.sourceChannelId&&s.status!=='failed')).length;existing.status=existing.streams.length?'available':'unavailable';existing.logo ||= channel.logo||'';existing.description ||= channel.description||'';existing.syncAt=Math.max(existing.syncAt??0,channel.syncAt??0);}return [...byId.values()];}
function normalizeEPG(channelId,programs){return programs.map((program,index)=>({programId:program.programId||createEpgProgramId(channelId,program.startTime??program.startAt??index,program.name??program.title),channelId,name:program.name??program.title??'',title:program.title??program.name??'',startTime:program.startTime??program.startAt??'',endTime:program.endTime??program.endAt??'',startAt:program.startAt??program.startTime??'',endAt:program.endAt??program.endTime??'',description:program.description??'',category:program.category??'',status:getEpgProgramStatus(program)}));}
function normalizeProtocol(protocol,url){const explicit=String(protocol??'').trim().toLowerCase();if(['hls/m3u8','application/vnd.apple.mpegurl','application/x-mpegurl'].includes(explicit))return 'hls';if(explicit && !['http','https','http/mp4','unknown','auto'].includes(explicit))return explicit;return inferLiveProtocolFromUrl(url);}

// Backward-compatible model aliases
export { createSourceChannelId, createStreamId, createEpgProgramId, createChannelIdentity, createChannelId };
export { createDisplayNameKey as createChannelIdentityKey };
